### ISSUE TITLE
Request for the dataset

### ISSUE THREAD

**Issue by hiddenguy1** [EshaanT/X-InSTA#2]
While running "data_process.ipynb",  the follewing error arised.
DefunctDatasetError: Dataset 'amazon_reviews_multi' is defunct and no longer accessible due to the decision of data providers.

Would you please tell me how to reach such datasets?

**Comment by EshaanT** [comment]
The data provider seems to have removed the dataset from huggingface. Please download the dataset from source [link](https://github.com/awslabs/open-data-docs/tree/main/docs/amazon-reviews-ml)
